version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: woogie
    restart: always
    ports:
      - "33068:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin"
      ]
    volumes:
      - ./be/src/mysql/init:/docker-entrypoint-initdb.d

networks:
  default:
    name: docker-study
