version: '3.1'

services:
  fe:
    build:
      dockerfile: ./Dockerfile.fe-dev  # React 앱을 빌드할 Dockerfile
    ports:
      - "3000:3000"  # React 개발 서버의 포트
    volumes:
      - ./fe:/app  # 로컬 소스 코드 디렉토리와 컨테이너 내부의 /app 디렉토리를 공유

  bff:
    build:
      dockerfile: ./Dockerfile.bff-dev
    ports:
      - "4100:5000"
    volumes:
      - ./bff:/app

  be:
    build:
      dockerfile: ./Dockerfile.be-dev
    volumes:
      - ./be:/app
    ports:
      - 4000:4000

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: woogie
    restart: always
    ports:
      - "33068:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin"
      ]
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  default:
    name: docker-study
