version: '3.1'

services:
  fe-web:
    volumes:
      - ./fe-web:/app  # 로컬 소스 코드 디렉토리와 컨테이너 내부의 /app 디렉토리를 공유
      - fe-web-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  be-for-frontend:
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_DEBUG=true

  be-board:
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start:dev"]

  be-logger:
    environment:
      - SPRING_PROFILES_ACTIVE=development
    # ports:
    #   - "5005:5005" # 원격 디버깅을 위한 포트 개방
    # command: ["java", "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n", "-jar", "/app/cube.jar"]

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: woogie

volumes:
  fe-web-node_modules: