version: '3.1'

services:
  fe:
    build:
      context: ./fe
      dockerfile: ./Dockerfile  # React 앱을 빌드할 Dockerfile
    ports:
      - "3000:3000"  # React 개발 서버의 포트
    volumes:
      - ./fe:/app  # 로컬 소스 코드 디렉토리와 컨테이너 내부의 /app 디렉토리를 공유

  bff:
    build:
      context: ./bff
      dockerfile: ./Dockerfile
    ports:
      - "4100:5000"
    volumes:
      - ./bff:/app

  be:
    build:
      context: ./be
      dockerfile: ./Dockerfile
    volumes:
      - ./be:/app
    ports:
      - 4000:4000

  logger:
    build:
      context: ./logger
      dockerfile: ./Dockerfile # Spring Boot 앱의 Dockerfile
    ports:
      - "4200:8080" # 호스트 포트와 컨테이너 포트 매핑
    environment:
      - SPRING_PROFILES_ACTIVE=development # 개발 모드 활성화

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: woogie
    restart: always
    ports:
      - "33068:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin"
      ]
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  default:
    name: docker-study
