version: '3.1'

services:
  fe-web:
    build:
      context: ./fe-web
      dockerfile: ./Dockerfile  # React 앱을 빌드할 Dockerfile
    ports:
      - "3000:3000"  # React 개발 서버의 포트

  be-for-frontend:
    build:
      context: ./be-for-frontend
      dockerfile: ./Dockerfile
    ports:
      - "4100:5000"
    volumes:
      - ./be-for-frontend:/app
      - /app/node_modules

  be-board:
    build:
      context: ./be-board
      dockerfile: ./Dockerfile
    volumes:
      - ./be-board:/app
      - /app/node_modules
    ports:
      - 4000:4000
    healthcheck:
      test: ["CMD", "node", "src/utils/healthcheck.util.mjs", "-t", "150"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 3s

  be-logger:
    build:
      context: ./be-logger
      dockerfile: ./Dockerfile # Spring Boot 앱의 Dockerfile
    ports:
      - "4200:8080" # 호스트 포트와 컨테이너 포트 매핑

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "33068:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin"
      ]
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  default:
    name: docker-study
