version: '3.1'

services:
  mysql:

  be-for-frontend:
    command: ["npm", "run", "start:dev"]

  be-logger:

  be-board:
    command: ["npm", "run", "start:dev"]

  fe-web:
    command: ["npm", "run", "start"]

networks:
  default:
    name: default_net