version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: localmysql1234
      # MYSQL_USER: root
    ports:
      - 33066:3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin",
      ]
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - default

  be-for-frontend:
    build:
      context: ./be-for-frontend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./be-for-frontend:/app
      - /app/node_modules
    env_file:
      - ./be-for-frontend/.env
    networks:
      - default

  be-logger:
    build:
      context: ./be-logger
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    # volumes:
    #   - ./be-logger:/app
    networks:
      - default

  be-board:
    build:
      context: ./be-board
      dockerfile: Dockerfile
    ports:
      - 4002:4002
    volumes:
      - ./be-board:/app
      - /app/node_modules
    env_file:
      - ./be-board/.env
    networks:
      - default

  fe-web:
    build:
      context: ./fe-web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./fe-web:/app
      - /app/node_modules
    env_file:
      - ./fe-web/.env
    networks:
      - default

networks:
  default:
    name: default_net