version: '3.1'

services:
  mysql:

  be-for-frontend:
    healthcheck:
      test: ["CMD", "node", "/utils/http-check.js", "http://localhost:4000/health"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s

  be-logger:

  be-board:
    healthcheck:
      test: ["CMD", "node", "/utils/http-check.js", "http://localhost:4002/health"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s

  fe-web:
    build:
      context: ./fe-web
      dockerfile: Dockerfile.prod
    healthcheck:
      test: ["CMD", "node", "/utils/http-check.js", "http://localhost:3000"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 5s

networks:
  default:
    name: default_net