# Use root as user credentials
version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: localmysql1234
      # MYSQL_USER: root
    ports:
      - 3306:3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin",
      ]
    networks:
      - default

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    # volumes:
    #   - ./bff:/app
    networks:
      - default

  logger:
    build:
      context: ./logger
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    # volumes:
    #   - ./logger:/app
    networks:
      - default

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 4002:4002
    # volumes:
    #   - ./be:/app
    networks:
      - default

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #   - ./fe:/app
    networks:
      - default

networks:
  default:
    name: default_net